name = "Vestiges of Tomorrow"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa4049c9b8b4457235333d3613c049a716c442f8834add81ce9104c2c05b9ce7"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
