name = "Vestiges of Tomorrow"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0e1a409e7c6b35003d193bbc0aa93526f5a8d858cc74df73cfb71a99a1395ff"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
