name = "Vestiges of Tomorrow"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0840e2280c6952401abf8237df00d21e22f5fd68728d932f5fec4994f8a9911e"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
