name = "Vestiges of Tomorrow"
version = "0.16.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c45cf7da278bf7b9a35ccd18ff519b08b10523039b5be300c03308b483d886c8"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
