name = "Vestiges of Tomorrow"
version = "0.10.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c2515cde3f84d3504e1b83cc92b8260d0d5156772d70f0a68a55b73dd3e0cc8"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
