name = "Vestiges of Tomorrow"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fae315e55be11cb47fabbed1378ec0757a6c5bccb51d1304d5aca49858fdd3c"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
