name = "Vestiges of Tomorrow"
version = "0.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "541659719f16a82b4b5953b72ed5bf897c4935df9ac0de1a5e64c6f3bb8ae432"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
