name = "Vestiges of Tomorrow"
version = "0.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c570c87274ddb10d42508d5d78984de19a228065441fbaedae2e6dba74dc5275"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
