name = "Vestiges of Tomorrow"
version = "0.14.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e404c9efe398c3c3e1c54257f029e672965526aaf61243b5bf7cf50d551e53d2"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
