name = "Vestiges of Tomorrow"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d424bd4d1edaeaac6e813ef1e3eb559dc4989d5617a5373e22e473dac7108477"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
