name = "Vestiges of Tomorrow"
version = "0.19.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16ee2cec28eef7deb02e7095a3e084a0f88b405d1274572097287136de6dd2df"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
