name = "Vestiges of Tomorrow"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e29151e7c73e88f94e3f843ff620541c2fc9baf84e54d4cf5353aaca243eb51b"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
