name = "Technomagus: The Quest for Power"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ca61c8c4908fc205db8ff9c731abc0cd9791227420120c9b413ac360c5d3ed5"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
