name = "Vestiges of Tomorrow"
version = "0.16.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dabb8c7cd4810119c24675b07768e21c8be4b6a565c8b2ab85a28b73a6ee1eef"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
