name = "Vestiges of Tomorrow"
version = "0.25.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df057f0cfe45e24660d15890c1e070a5ccad90a7e7623864dc95ab329ad26bf6"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
