name = "Vestiges of Tomorrow"
version = "0.8.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30a31aaf146fa0ba970bbcaec834f725440c910a87651350cf2d4994d1a4b653"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
