name = "Vestiges of Tomorrow"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab92958ca7135607fe3b96423f6f3dc1c73a533683c37d4ab2fc28a426e9155a"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
