name = "Vestiges of Tomorrow"
version = "0.8.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d553777406bf11517356f6b844d57694e7da4a91667a9a43cb89dec1d9fd1d36"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
