name = "Vestiges of Tomorrow"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df3dc918dd2441d582c29c7ed162a1aa71a817585a81806918445aaceb820dad"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
