name = "Vestiges of Tomorrow"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01c55026393a90f23fe966e4767d2e279caf991e002738ff10f50f8b71a30a8e"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
