name = "Vestiges of Tomorrow"
version = "0.8.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94e3d1c7890cd92328825401bfb9c6d1466844f08cca9df103c15df9e5760b0e"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
