name = "Vestiges of Tomorrow"
version = "0.25.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "118bc02b13375fccfb8bcdb4622d2cd1154649c84c82df11dc9cba6451e04dea"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
