name = "Vestiges of Tomorrow"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67a099be16f838f53de3b353d6cb82a83e310662117c67121242f7d86a8b2ea9"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
