name = "Vestiges of Tomorrow"
version = "0.18.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81feb10d5b685c44592c893d2ba2a0c69d8728eac58beb3977c6bda2d3bb9b28"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
