name = "Vestiges of Tomorrow"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37c906757943081ea9495d377af2fbf81428172b939ea0ccc58cdf308f29ac91"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
