name = "Vestiges of Tomorrow"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf389b09be075ac3c2af6d1ae2a07f0b2e674915fb957f327ac5ee7c240d203f"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
