name = "Vestiges of Tomorrow"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c175732f4c2e8bedbb192e75dd7d0f3889f25862e5d2328046642f71dc25e94b"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
