name = "Vestiges of Tomorrow"
version = "0.25.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "169f634ec570e447fbe72febb6352e1a874314dc97fdf31748c1061c17ba6034"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
