name = "Vestiges of Tomorrow"
version = "0.25.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f645cb5075e30515dc71d15a7afbd3608dfff2fe3a79fc1cd0f66737492eea60"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
