name = "Vestiges of Tomorrow"
version = "0.23.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d71dc5298733075e6f7f350be89529cfa95aabd36e4a003e010b39045c9dcb24"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
