name = "Vestiges of Tomorrow"
version = "0.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a7b0e1490e0fec1e1d27cc44d0cc4dec82602c13222938209258fd76cbda0e8"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
