name = "Vestiges of Tomorrow"
version = "0.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24535866c20a043ff76722d19cba8a730b1689d0624b39b94ea0e5d9b535f33d"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
