name = "Vestiges of Tomorrow"
version = "0.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06a9b6d1eb17e0184f92935a0cef7c071169ffbace255dcb96e240adae6f66da"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
