name = "Vestiges of Tomorrow"
version = "0.11.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46e1a89b3edce36febf07f5223170f3ff32ed9d70545ea698f3c7321626bbad8"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
