name = "Vestiges of Tomorrow"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "917d2c49af1a8b739a75b4bbb3364e7c33e1ed166d1afc7ba6eeea867ec2a100"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
