name = "Vestiges of Tomorrow"
version = "0.19.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eef402d8afd7bf4fd1f4b45e7f307751b5fe9396b3d0ce58fce5a0b62176feb3"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
