name = "Vestiges of Tomorrow"
version = "0.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6d6955644419ae12b77aa331c0aa1b139c3fa93598d26546a3cc4aeb56c1863"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
