name = "Vestiges of Tomorrow"
version = "0.8.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a624d4dedc7c849ec7c91c2c0dc8fdb62fc94b50654d2ce318b211a14009e881"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
