name = "Vestiges of Tomorrow"
version = "0.24.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f81ecc3250de02fc69d29cd69a848af18aee00cb9777342b463a47995797908f"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
