name = "Vestiges of Tomorrow"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38dc76d9d14d811290126a8d85682e7f69a09e667e9cbd6bbb62aee33b24a7d0"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
