name = "Vestiges of Tomorrow"
version = "0.25.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "646790de0a6fc86904ad0e8230821a51e4dd6a2773c5a50a551b8d499b913d71"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
