name = "Vestiges of Tomorrow"
version = "0.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65b4904beb1f090b24de180c63e6390e6cbfaeb0fe91b818944475e642573c90"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
