name = "Vestiges of Tomorrow"
version = "0.27.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e3e336915cb30de4a2d771c060ea411dc125412f3ee063033498994f607ccc6"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
