name = "Vestiges of Tomorrow"
version = "0.28.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c467fe0b535d13c2e02e6228cef665815a98d5b2040617a61f0bdafd35a6215"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
