name = "Vestiges of Tomorrow"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f626d8b2b44c5da84636ed84dc67944e56e62745f480ef363ef87b8464aae265"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
