name = "Vestiges of Tomorrow"
version = "0.20.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2e6328eb040926176cb5f7199a7ea6c9fe1a4aeed068d7a53c0867a6c1d45c5"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
