name = "Vestiges of Tomorrow"
version = "0.25.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adbe56a0ef9a7eda65d5dea499d797c941923bdf854fef75f3871ade547475d7"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
