#Amount of ticks for block selection cooldown (default = 2s - 40)
#Range: 0 ~ 12096000
SelectionCooldown = 40
#Amount of ticks that get added to the block selection cooldown (default = 0)
#Range: 0 ~ 12096000
SelectionAddedCooldown = 0
#Add range for block selection (default = 12)
#Range: -8 ~ 128
SelectionMaxRange = 12
#Maximum number of blocks that can be selected (default = 64)
#Range: 1 ~ 2048
SelectionMaxBlock = 64
#Require Hunger for said selected blocks (default = true)
RequiresHunger = true
#Causes Food Loss to be Multiplied when mining amount of  blocks (default = 2.0)
#Range: 0.0 ~ 1000.0
FoodExhaustionMultiplier = 1
#Require XP for said selected blocks (default = false)
RequiresXP = false
#Amount of XP ''Points'' to be taken when mining for said block in selection (default = 0)
#Range: > 0
XPExhaustionAmount = 0
#Require Fuel for said selected blocks (default = false)
RequiresFuelItem = false
#Takes said Vein miner Item Fuel Amount for every Interact/Destroyable Blocks (default = 0)
#Range: > 0
FuelExhaustionAmount = 0
#Amount of ticks for till you are able to pick up items after blocks drops from selection (default = 0)
#Range: 0 ~ 30000
ItemPickupDelay = 0
#Amount of ticks for till next block gets broken (default = 5)
#Range: 0 ~ 100
DelayBetweenBreak = 5
#Amount of blocks between broken blocks (default = 4)
#Range: 1 ~ 256
BlockPerBreak = 4
#Waits for all blocks to be broken before doing another selection (default = true)
WaitTillBroken = true
#Invert the whitelist behavior (default = true)
InvertWhitelist = true
#Require Hand/Tools for said selected blocks that requires hand/tools to drop (default = true)
RequiresMineable = true
#Require Tools for said selected blocks (default = false)
RequiresTools = true
#Prevents Tools being broke when mining/interaction (default = true)
PreventBreakingTool = true
#Sends all dropped Items from Blocks to the Player (default = true)
SendBlocksToPlayer = true
#Ability to Place Blocks by Selection (default = false)
BlockPlacing = false
#Ability to Interact Blocks using said Hand by Selection (default = true)
HandInteraction = true
#Ability to Interact Blocks using said Item by Selection (default = true)
ItemInteraction = true
#Ability to Allow Players to see there selection through Blocks (default = true)
XrayOutlineSelection = true
#Ability to Interact Blocks using said Item by Selection (default = false)
NoDurabilityLoss = false
#List of block tags for vein mining as in Start Pos Block Tag needs to match said block in selection with the same tag.
VeinBlockTags = [
  "forge:ores",
  "forge:glass_panes",
  "forge:sands",
  "forge:end_stones",
  "forge:cobblestones",
  "forge:gravels",
  "forge:netherracks",
  "forge:obsidians",
  "forge:stones",
  "minecraft:leaves",
  "minecraft:crops",
  "minecraft:coral_blocks",
  "minecraft:sand",
  "minecraft:dirt",
  "minecraft:logs",
  "minecraft:base_stone_overworld",
  "minecraft:base_stone_nether",
]
