# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build Zip
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Install dependencies
      run: sudo apt install zip

    - name: Download packwiz artifact
      id: download-artifact
      uses: actions/download-artifact@v4
      with:
        repository: packwiz/packwiz
        run-id: 11331794723
        name: "Linux 64-bit x86"
        path: ~/packwiz.zip

    - name: list files
      run: ls -la ~ ;; file ~/packwiz.zip

    # - uses: actions/checkout@v4
    # - name: Set up JDK 1121
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '21'
    #     distribution: 'adopt'

