# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build Zip
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Install dependencies
      run: sudo apt-get install zip unzip

    - uses: robinraju/release-downloader@v1
      with:
        repository: freshautomations/stoml
        latest: true
        fileName: stoml_linux_amd64

    - name: Ensure ~/.local/bin exists
      run: mkdir -p ~/.local/bin

    - run: mv stoml_linux_amd64 ~/.local/bin/stoml && chmod +x ~/.local/bin/stoml

    - name: Download packwiz artifact
      uses: dawidd6/action-download-artifact@v5
      with:
        repo: packwiz/packwiz
        run_id: 11331794723
        name: Linux 64-bit x86
        skip_unpack: true

    - name: Unzip packwiz
      run: unzip "Linux 64-bit x86.zip" -d ~/.local/bin

    - name: Include ~/.local/bin in path
      run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Remove unnecessary artifact
      run: rm "Linux 64-bit x86.zip"

    - name: Checkout the repo.
      uses: actions/checkout@v4

    - name: Get modpack version
      uses: mathiasvr/command-output@v2.0.0
      id: version
      with:
        run: stoml pack.toml version

    - name: build zip
      run: packwiz curseforge export

    - name: Workaround for Github odd behavior
      run: mkdir ~/dist && unzip "*.zip" -d ~/dist

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: "Vestiges_of_Tomorrow_v${{ steps.version.outputs.stdout }}"
        path: ~/dist
        retention-days: 90
