# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build Zip
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Install dependencies
      run: sudo apt-get install zip unzip
    - name: Ensure ~/.local/bin exists
      run: mkdir -p ~/.local/bin

    - name: Download packwiz artifact
      uses: dawidd6/action-download-artifact@v5
      with:
        repo: packwiz/packwiz
        run_id: 11331794723
        name: Linux 64-bit x86
        skip_unpack: true

    - name: Unzip packwiz
      run: unzip "Linux 64-bit x86.zip" -d ~/.local/bin

      # im going insane
    - run: ls -la ~/.local/bin
    - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Remove unnecessary artifact
      run: rm "Linux 64-bit x86.zip"

    - uses: actions/checkout@v4
    - name: build zip
      run: packwiz curseforge export

    - run: ls -la

